### ISSUE TITLE
Uncaught (in promise) ReferenceError: nethereumUnityInstance is not defined at _EnableEthereum

### ISSUE THREAD

**Issue by AnhPham** [Nethereum/Nethereum.Unity.Webgl#2]
Unity Editor: 2021.2.10
API Compatibility Level: .Net Framework
Build WebGL: OK
Run on web: Error
`Uncaught (in promise) ReferenceError: nethereumUnityInstance is not defined     at _EnableEthereum`

**Comment by juanfranblanco** [comment]
You need to define the variable in your html page see: https://github.com/Nethereum/Nethereum.Unity.Webgl/issues/1
